FROM balenalib/%%BALENA_MACHINE_NAME%%:bullseye

RUN install_packages libraspberrypi-bin

RUN install_packages motion
COPY motion.conf /etc/motion/motion.conf

EXPOSE 8080
EXPOSE 8081/tcp
EXPOSE 8081/udp

CMD motion -c /etc/motion/motion.conf
