version: "2"
volumes:
  media:
services:
  motion:
    build: ./motion
    devices:
      - /dev/video0:/dev/video0
      - /dev/vchiq:/dev/vchiq
    volumes:
      - media:/safaricam/media
    working_dir: /safaricam/media
    ports:
      - "8080:8080"
      - "80:80/tcp"
      - "80:80/udp"
    restart: unless-stopped
  gphotos:
    build: ./gphotos
    volumes:
      - media:/safaricam/media/Safaricam
    environment:
      - GPHOTOS_CLI_TOKENSTORE_KEY
    restart: unless-stopped
  nightvision:
    build: ./nightvision
    devices:
      - /dev/gpiomem:/dev/gpiomem
  disable-led:
    image: busybox
    devices:
      - /sys/class/leds/led0:/sys/class/leds/led0
    restart: no
    command: |
      echo none > /sys/class/leds/led0/trigger
      echo 1 > /sys/class/leds/led0/brightness
      tail -f /dev/null
